version: '3.8'

services:
  front:
    build:
      context: .
      args:
        API_URL: "http://$DEV_HOST:3000"
    command: "yarn run dev"
    volumes:
      - .:/app
    ports:
      - "$FRONT_PORT:3000"